apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  namespace: my-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: my-docker-repo/my-microservice:latest
        ports:
        - containerPort: 5000
        env:
        - name: ENV
          value: "production"
