apiVersion: v1
kind: Service
metadata:
  name: microservice
  namespace: my-namespace
spec:
  selector:
    app: microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
